name: WakaTime Stats

on:
  # Run every day at 00:30 UTC
  schedule:
    - cron: '30 0 * * *'

  # Allows manual trigger
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update README
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ░▒▓█
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_MASKED_TIME: false
